name: Code Quality Checks and Tests

# Trigger this workflow on pull requests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]
    types: [opened, reopened, synchronize]

jobs:
  code_quality_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Run Unimported Check
        run: npm run unimported:check
